/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERATION = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int FUNCDEF = 3;
  /** RegularExpression Id. */
  int FUNCNAME = 4;
  /** RegularExpression Id. */
  int PARAMNAME = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int SP = 7;
  /** RegularExpression Id. */
  int OPENBRACKET = 8;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 9;
  /** RegularExpression Id. */
  int OPENCBRACKET = 10;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OPERATION>",
    "<NUMBER>",
    "\"DEF\"",
    "<FUNCNAME>",
    "<PARAMNAME>",
    "<EOL>",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
