/* Generated By:JavaCC: Do not edit this line. ForteLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ForteLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPARATOR_OP = 1;
  /** RegularExpression Id. */
  int BOOLEAN_OP = 2;
  /** RegularExpression Id. */
  int SET_OP = 3;
  /** RegularExpression Id. */
  int OP = 4;
  /** RegularExpression Id. */
  int CONCAT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int CONTAINS = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int FLOATING_POINT_NUMBER = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int REGEX_STRING = 12;
  /** RegularExpression Id. */
  int INCLUDE = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int MATCH = 15;
  /** RegularExpression Id. */
  int EXEC = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int INPUT = 18;
  /** RegularExpression Id. */
  int INPUTBOX = 19;
  /** RegularExpression Id. */
  int OPENBRACKET = 20;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 21;
  /** RegularExpression Id. */
  int OPENSBRACKET = 22;
  /** RegularExpression Id. */
  int CLOSESBRACKET = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int CAPS = 25;
  /** RegularExpression Id. */
  int ENUM_OPEN = 26;
  /** RegularExpression Id. */
  int ENUM_CLOSE = 27;
  /** RegularExpression Id. */
  int EQUALS = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int OPENCBRACKET = 30;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 31;
  /** RegularExpression Id. */
  int NUM = 32;
  /** RegularExpression Id. */
  int LST = 33;
  /** RegularExpression Id. */
  int SET = 34;
  /** RegularExpression Id. */
  int FUN = 35;
  /** RegularExpression Id. */
  int BOO = 36;
  /** RegularExpression Id. */
  int STR = 37;
  /** RegularExpression Id. */
  int COLON = 38;
  /** RegularExpression Id. */
  int VAR_NAME = 39;
  /** RegularExpression Id. */
  int FUNCTION_ARROW = 40;
  /** RegularExpression Id. */
  int GUARD_START = 41;
  /** RegularExpression Id. */
  int GUARD = 42;
  /** RegularExpression Id. */
  int GUARD_ARROW = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BlockComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMPARATOR_OP>",
    "<BOOLEAN_OP>",
    "<SET_OP>",
    "<OP>",
    "\"++\"",
    "\".\"",
    "\"?\"",
    "<NUMBER>",
    "<FLOATING_POINT_NUMBER>",
    "<BOOLEAN>",
    "<STRING>",
    "<REGEX_STRING>",
    "\"include\"",
    "\"in\"",
    "\"match\"",
    "\"@exec\"",
    "\"@print\"",
    "\"@input\"",
    "\"@inputbox\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<CAPS>",
    "\" {|\"",
    "\"|}\"",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"num\"",
    "\"list\"",
    "\"set\"",
    "\"func\"",
    "\"bool\"",
    "\"str\"",
    "\":\"",
    "<VAR_NAME>",
    "\"->\"",
    "\"|>\"",
    "\"|\"",
    "\"->>\"",
    "<token of kind 44>",
    "<token of kind 45>",
    "\"#[\"",
    "\"#[\"",
    "<token of kind 48>",
    "\"]#\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
  };

}
