/* Generated By:JavaCC: Do not edit this line. ForteLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ForteLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERATION = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int FLOATING_POINT_NUMBER = 3;
  /** RegularExpression Id. */
  int VAR_NAME = 4;
  /** RegularExpression Id. */
  int OPENBRACKET = 5;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 6;
  /** RegularExpression Id. */
  int OPENCBRACKET = 7;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int FUNCTION_ARROW = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OPERATION>",
    "<NUMBER>",
    "<FLOATING_POINT_NUMBER>",
    "<VAR_NAME>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"->\"",
    "<token of kind 12>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
  };

}
